#!/usr/bin/env sh

JEST_CONFIG_FILE="jest.config.mjs"
PACKAGE_LOCK_FILE="package-lock.json"

if [ -f $JEST_CONFIG_FILE ]; then
  echo
  echo "$JEST_CONFIG_FILE exists"
else
  npm i -D jest@27 #nodemon@2.0
  npx jest --init
fi

if [ -f $PACKAGE_LOCK_FILE ]; then
  echo
  echo "$PACKAGE_LOCK_FILE exists"
  npm ci --silent
else
  npm i pino@6.8 pino-pretty@5.1 socket.io@4.1 pretty-bytes@5.6
  npm install --silent
fi

clear
